### ISSUE TITLE
When using {{.Name}} the same firmware is re-downloaded.

### ISSUE THREAD

**Issue by ClassicUA** [cj123/allthefirmwares#8] opened 2018-10-27 11:18 UTC
#7

**Comment by cj123** [comment] 2018-10-27 11:33
this occurs because of apple's new combined ipsw files.

making allthefirmwares exclude or specially treat these files isn't worth the complexity that it will bring.

closing as duplicate of #7.

**Closed as completed by cj123** 2018-10-27 11:33 UTC
Labels: duplicate, wontfix
